# Generated by Django 4.0 on 2024-04-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageelement',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
