# Generated by Django 4.0 on 2024-04-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0002_imageelement_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageelement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
